# Default values for s4dbs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# frontendConfigMode should not be changed unless you are advised to by support team
frontendConfigMode: false

### START * not needed if frontendConfigMode set to false ###
# serverHostname is the public available dns / server name - e.g. route in an openshift 
serverHostname: localhost ##enter dns name of route here (will be created later) ##

# servicePort is the public service /rest-api port for the frontend to redirect correctly - change to 8080 (port of reverse proxy) if not using a route or ingress up front s4dbs
servicePort: 80

# serverProtokol depends on your configmap for reverse proxy / nginx
serverProtokol: http

# grafanaPort is the public grafana port for the frontend to redirect correctly - change to 8080/grafana (port of reverse proxy) if not using a route or ingress up front s4dbs
grafanaPort: 80/grafana

### END * not needed if frontendConfigMode set to false ###

# pdb is the overall repository (aka pdb) configuration
pdb:
  pdbDbName: speedgain
  pdbHost: s4dbs-postgres-service
  pdbPort: 5432
  pdbUser: postgres

# s4dbsCollectorDeployment defines collector image and varas
s4dbsCollectorDeployment:
  image: itgainis/s4dbs_collector:1.5.0
  spgLogLevel: INFO

# s4dbsPostgresDeployment defines timescale image and varas
s4dbsPostgresDeployment: 
  image: timescale/timescaledb:2.11.2-pg13
  persistentVolumeClaimName: s4dbs-postgres-pv-claim
  persistentVolumeClaimSize: 100G
  storageClassName: something #change to map you storage provider, like managed-csi on AZURE or thin on OpenShift

# s4dbsServiceDeployment defines timescale image and varas
s4dbsServiceDeployment: 
  image: itgainis/s4dbs_service:1.5.0
  port: 8080

# s4dbsGrafanaDeployment defines timescale image and varas
s4dbsGrafanaDeployment: 
  image: itgainis/s4dbs_grafana:1.5.0
  port: 3000
  anonymousLogin: false
  
# s4dbsFrontendDeployment defines timescale image and varas
s4dbsFrontendDeployment: 
  image: itgainis/s4dbs_frontend:1.5.0
  port: 8080

# s4dbsReverseDeployment defines timescale image and varas 
s4dbsReverseDeployment: 
  image: nginx:1.23
  port: 8080
  publicPort: 80
