# Default values for s4dbs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serverHostname: ##enter dns name of route here (will be created later) ##
serverPort: 30805
serverProtokol: http
frontendConfigMode: true

pdb:
  pdbDbName: speedgain
  pdbHost: s4dbs-postgres-service
  pdbPass: ##PasswordOfPostgresUser##
  pdbPort: 5432
  pdbUser: postgres

s4dbsCollectorDeployment:
  image: itgainis/s4dbs_collector:1.4.0
  spgLogLevel: DEBUG

s4dbsPostgresDeployment: 
  image: timescale/timescaledb:2.5.1-pg13
  persistentVolumeClaimName: s4dbs-postgres-pv-claim
  
s4dbsServiceDeployment: 
  image: itgainis/s4dbs_service:1.4.0
  port: 8080

s4dbsGrafanaDeployment: 
  image: itgainis/s4dbs_grafana:1.4.0
  port: 3000
  persistentVolumeClaimName: s4dbs-grafana-pv-claim
  persistentVolumeClaimNameDashboards: s4dbs-grafana-dashboards-pv-claim
  
s4dbsFrontendDeployment: 
  image: itgainis/s4dbs_frontend:1.4.0
  port: 8080
  
s4dbsReverseDeployment: 
  image: nginx:1.23
  port: 8080
