{{- if .Values.s4dbsReverseDeployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: s4dbs-reverse
  name: s4dbs-reverse-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: s4dbs-reverse
  template:
    metadata:
      labels:
        app: s4dbs-reverse
    spec:
      containers:
      - name: s4dbs-reverse
        image: {{ .Values.s4dbsReverseDeployment.image }}
        ports:
        - containerPort: {{ .Values.s4dbsReverseDeployment.port  | default "8080" }}
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            name: s4dbs-nginx-conf
            readOnly: true

        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.s4dbsReverseDeployment.port  | default "8080" }}
          failureThreshold: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.s4dbsReverseDeployment.port  | default "8080" }}
          failureThreshold: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: {{ .Values.s4dbsReverseDeployment.port  | default "8080" }}
          failureThreshold: 60
          periodSeconds: 10
          
        resources:
          requests:
            memory: {{ .Values.s4dbsReverseDeployment.requests_memory | quote }}
            cpu: {{ .Values.s4dbsReverseDeployment.requests_cpu | quote }}
          limits:
            memory: {{ .Values.s4dbsReverseDeployment.limits_memory | quote }}
            cpu: {{ .Values.s4dbsReverseDeployment.limits_cpu | quote }}
      restartPolicy: Always
      volumes:
      - name: s4dbs-nginx-conf
        configMap:
          name: s4dbs-nginx-conf
{{- end }}
---
{{- if .Values.s4dbsReverseDeployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: s4dbs-reverse-service
spec:
  selector:
    app: s4dbs-reverse
  type: {{ .Values.s4dbsReverseDeployment.external_traffic_service_type | default "LoadBalancer" }}
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: {{ .Values.s4dbsReverseDeployment.publicPort  | default "80" }}
      targetPort: {{ .Values.s4dbsReverseDeployment.port  | default "8080" }}
{{- end }}
---
{{- if and .Values.s4dbsReverseDeployment.enabled ( .Capabilities.APIVersions.Has "route.openshift.io/v1/Route") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: s4dbs
spec:
  to:
    kind: Service
    name: s4dbs-reverse-service
  port:
    targetPort: {{ .Values.s4dbsReverseDeployment.port  | default "8080" }}
{{- end }}