{{- if not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace .Values.s4dbsPostgresDeployment.persistentVolumeClaimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.s4dbsPostgresDeployment.persistentVolumeClaimName }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.s4dbsPostgresDeployment.storageClassName  | default "managed-csi" }} 
  # edit storage class name according to your k8s provider in values.yaml
  resources:
    requests:
      storage: {{ .Values.s4dbsPostgresDeployment.persistentVolumeClaimSize }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: s4dbs-postgres
  name: s4dbs-postgres-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: s4dbs-postgres
  template:
    metadata:
      labels:
        app: s4dbs-postgres
    spec:
      volumes:
      - name: postgres-pv-storage
        persistentVolumeClaim:
          claimName: {{ .Values.s4dbsPostgresDeployment.persistentVolumeClaimName }}
      initContainers:
      - name: s4dbs-postgres-migration
        image: {{ .Values.s4dbsPostgresDeployment.image }}
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: s4dbs-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: speedgain
        - name: OLD_DATA_DIR
          value: /var/lib/postgresql/data/pgdata
        - name: NEW_DATA_DIR
          value: /var/lib/postgresql/data/pgdata/16
        - name: INIT_CONTAINER
          value: "true"
        resources:
          requests:
            memory: {{ .Values.s4dbsPostgresDeployment.requests_memory | quote }}
            cpu: {{ .Values.s4dbsPostgresDeployment.requests_cpu | quote }}
          limits:
            memory: {{ .Values.s4dbsPostgresDeployment.limits_memory | quote }}
            cpu: {{ .Values.s4dbsPostgresDeployment.limits_cpu | quote }}
        volumeMounts:
        - name: postgres-pv-storage
          mountPath: /var/lib/postgresql/data/
      containers:
      - name: s4dbs-postgres
        image: {{ .Values.s4dbsPostgresDeployment.image }}
        ports:
        - containerPort: {{ .Values.pdb.pdbPort  | default "5432" }}
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: s4dbs-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: speedgain
        - name: NEW_DATA_DIR
          value: /var/lib/postgresql/data/pgdata/16
        
        readinessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-h", "localhost", "-d", "postgres", "-c", "SELECT 1"]
          failureThreshold: 60
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-h", "localhost", "-d", "postgres", "-c", "SELECT 1"]
          failureThreshold: 5
          periodSeconds: 10
        startupProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-h", "localhost", "-d", "postgres", "-c", "SELECT 1"]
          failureThreshold: 60
          periodSeconds: 10

        resources:
          requests:
            memory: {{ .Values.s4dbsPostgresDeployment.requests_memory | quote }}
            cpu: {{ .Values.s4dbsPostgresDeployment.requests_cpu | quote }}
          limits:
            memory: {{ .Values.s4dbsPostgresDeployment.limits_memory | quote }}
            cpu: {{ .Values.s4dbsPostgresDeployment.limits_cpu | quote }}
        volumeMounts:
        - name: postgres-pv-storage
          mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: s4dbs-postgres-service
spec:
  selector:
    app: s4dbs-postgres
  ports:
    - protocol: TCP
      port: {{ .Values.pdb.pdbPort  | default "5432" }}
      targetPort: {{ .Values.pdb.pdbPort  | default "5432" }}
