{{- if not (lookup "v1" "Secret" .Release.Namespace "s4dbs-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: s4dbs-secrets
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  postgres-password: {{ randAlphaNum 32 }}
  mcp-password: {{ randAlphaNum 32 }}
{{- end }}

{{- if and ( not .Values.s4dbsReverseDeployment.sslCertManual ) ( and .Values.s4dbsReverseDeployment.sslCertKey .Values.s4dbsReverseDeployment.sslCertFullchain ) }} 
apiVersion: v1
kind: Secret
metadata:
  name: s4dbs-ssl-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.s4dbsReverseDeployment.sslCertFullchain  | b64enc | quote }}
  tls.key: {{ .Values.s4dbsReverseDeployment.sslCertKey        | b64enc | quote }}
{{- end }}