{{- if not (lookup "v1" "Secret" .Release.Namespace "s4dbs-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: s4dbs-secrets
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  postgres-password: {{ randAlphaNum 32 }}
{{- end }}