apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: s4dbs-frontend
  name: s4dbs-frontend-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: s4dbs-frontend
  template:
    metadata:
      labels:
        app: s4dbs-frontend
    spec:
      containers:
      - name: s4dbs-frontend
        image: {{ .Values.s4dbsFrontendDeployment.image }}
        ports:
        - containerPort: {{ .Values.s4dbsFrontendDeployment.port | default "8080" }}
        imagePullPolicy: Always
        env:
          - name: FRONTEND_CONFIG_MODE
            value: {{ .Values.frontendConfigMode | default "false" | quote }}
          - name: SERVICE_PROTOCOL
            value: {{ .Values.serverProtokol | default "http" }}
          - name: SERVICE_HOST
            value: {{ .Values.serverHostname | default "notneeded" }}
          - name: SERVICE_PORT
            value: {{ .Values.servicePort | default "notneeded" | quote }}
          - name: GRAFANA_PROTOCOL
            value: {{ .Values.serverProtokol | default "notneeded" }}
          - name: GRAFANA_HOST
            value: {{ .Values.serverHostname | default "notneeded" }}
          - name: GRAFANA_PORT
            value: {{ .Values.grafanaPort | default "notneeded" | quote }}

        readinessProbe:
          httpGet:
            path: /s4dbs-ui
            port: 8080
          failureThreshold: 60
          periodSeconds: 10
        livenessProbe: 
          httpGet:
            path: /s4dbs-ui
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /s4dbs-ui
            port: 8080
          failureThreshold: 60
          periodSeconds: 10
          
        resources:
          requests:
            memory: {{ .Values.s4dbsFrontendDeployment.requests_memory | quote }}
            cpu: {{ .Values.s4dbsFrontendDeployment.requests_cpu | quote }}
          limits:
            memory: {{ .Values.s4dbsFrontendDeployment.limits_memory | quote }}
            cpu: {{ .Values.s4dbsFrontendDeployment.limits_cpu | quote }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: s4dbs-frontend-service
spec:
  selector:
    app: s4dbs-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.s4dbsFrontendDeployment.port | default "8080" }}
      targetPort: {{ .Values.s4dbsFrontendDeployment.port | default "8080" }}
