apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: s4dbs-collector
  name: s4dbs-collector-deployment
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: s4dbs-collector
  template:
    metadata:
      labels:
        app: s4dbs-collector
    spec:
      containers:
      - name: s4dbs-collector
        image: {{ .Values.s4dbsCollectorDeployment.image }}
        imagePullPolicy: Always
        env:
          - name: PDB_DB_NAME
            value: {{ .Values.pdb.pdbDbName | default "speedgain" }}
          - name: PDB_HOST
            value: {{ .Values.pdb.pdbHost | default "s4dbs-postgres-service" }}
          - name: PDB_PASS
            valueFrom: 
             secretKeyRef:
               name: s4dbs-secrets
               key: postgres-password
          - name: PDB_PORT
            value: {{ .Values.pdb.pdbPort | default "5432" | quote }}
          - name: PDB_USER
            value: {{ .Values.pdb.pdbUser | default "postgres" }}
          - name: SPGLOGLEVEL
            value: {{ .Values.s4dbsCollectorDeployment.spgLogLevel | default "Info" }}
      restartPolicy: Always
