apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: s4dbs-frontend
  name: s4dbs-frontend-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: s4dbs-frontend
  template:
    metadata:
      labels:
        app: s4dbs-frontend
    spec:
      containers:
      - name: s4dbs-frontend
        image: {{ .Values.s4dbsFrontendDeployment.image }}
        ports:
        - containerPort: {{ .Values.s4dbsFrontendDeployment.port }}
        imagePullPolicy: Always
        env:
          - name: FRONTEND_CONFIG_MODE
            value: {{ .Values.frontendConfigMode | quote }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: s4dbs-frontend-service
spec:
  selector:
    app: s4dbs-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.s4dbsFrontendDeployment.port }}
      targetPort: {{ .Values.s4dbsFrontendDeployment.port }}
